### PR TITLE
WIP: Prepare for release

### PR DESCRIPTION
**Pull request by Michael-F-Bryan**
Miscellaneous jobs required to do a release.

- Update the README to mention `nightly`
- Switch licence from Apache-2.0 to a MIT/Apache-2.0 dual license
  - @Centril, are you okay with this?
- Update `Cargo.toml` metadata
- Enable travis to make sure breaking `nightly` changes are detected early

### CODE REVIEW

**Comment by Michael-F-Bryan** [comment]
@Centril, it doesn't look like I can enable travis because I'm not the repo owner. Would you be able to enable it and set up "cron job" so it rebuilds `master` every week or so?

**Comment by Centril** [comment]
> * @Centril, are you okay with this?

Certainly!

> @Centril, it doesn't look like I can enable travis because I'm not the repo owner. Would you be able to enable it and set up "cron job" so it rebuilds `master` every week or so?

Enabled travis and setup a weekly cron job. :)

**Comment by Michael-F-Bryan** [comment]
[Released!](https://docs.rs/safe/0.1.0/safe/) :tada:

**Comment by Centril** [comment]
🎉 🎈 🍾 

Thanks a lot for driving this!

**Pull request merged**
